version: '3.8'
services:
  backend:
    build: ./backend
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - django-network
  nginx:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
        - django-network
networks:
  django-network:
    name: django-network