# Generated by Django 4.1.5 on 2023-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_rename_status_crust_crustsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crust',
            old_name='crustSize',
            new_name='status',
        ),
    ]
