# Generated by Django 4.1.5 on 2023-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_rename_crustsize_crust_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crust',
            name='status',
            field=models.CharField(choices=[('thin', 'thin'), ('normal', 'normal'), ('thick', 'thick'), ('gluten free', 'gluten free')], default='normal', max_length=32, verbose_name='Choose Crust Size'),
        ),
    ]
