# Generated by Django 4.1.5 on 2023-02-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_cheese_pizza_chicken_pizza_ham_pizza_mushrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crust',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza.crust'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza.sauce'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza.size'),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
