# Generated by Django 4.1.5 on 2023-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0007_alter_cheese_name_alter_crust_name_alter_pizza_crust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crust',
            name='name',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
