# Generated by Django 4.1.5 on 2023-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0008_alter_crust_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crust',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
