# Generated by Django 4.1.5 on 2023-02-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0010_cardnumber_cvv_expiration_carddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnumber',
            name='name',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cvv',
            name='name',
            field=models.IntegerField(),
        ),
    ]
