# Generated by Django 4.1.5 on 2023-02-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0011_alter_cardnumber_name_alter_cvv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cardnumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza.cardnumber'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza.cvv'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza.expiration'),
        ),
    ]
