# Generated by Django 4.1.5 on 2023-02-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0012_alter_carddetails_cardnumber_alter_carddetails_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cardnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.cardnumber'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.cvv'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.expiration'),
        ),
    ]
