# Generated by Django 4.1.5 on 2023-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0013_alter_carddetails_cardnumber_alter_carddetails_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiration',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expiration',
            name='year',
            field=models.IntegerField(),
        ),
    ]
