# Generated by Django 4.1.5 on 2023-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0015_alter_cardnumber_name_alter_cvv_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnumber',
            name='name',
            field=models.CharField(max_length=19),
        ),
    ]
