# Generated by Django 4.1.5 on 2023-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0016_alter_cardnumber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cardnumber',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiration',
            field=models.CharField(max_length=19),
        ),
        migrations.DeleteModel(
            name='CardNumber',
        ),
        migrations.DeleteModel(
            name='CVV',
        ),
        migrations.DeleteModel(
            name='Expiration',
        ),
    ]
