# Generated by Django 4.1.5 on 2023-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0017_alter_carddetails_cardnumber_alter_carddetails_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.CharField(max_length=3, verbose_name='MMYY'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiration',
            field=models.CharField(max_length=4),
        ),
    ]
