# Generated by Django 4.1.5 on 2023-02-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0018_carddetails_name_alter_carddetails_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.CharField(help_text='MMYY', max_length=3),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='name',
            field=models.TimeField(max_length=50),
        ),
    ]
