# Generated by Django 4.1.5 on 2023-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0019_alter_carddetails_cvv_alter_carddetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
