# Generated by Django 4.1.5 on 2023-02-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0022_carddetails_address_carddetails_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='address2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
