# Generated by Django 4.1.5 on 2023-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0023_rename_address_carddetails_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='address1',
            field=models.CharField(max_length=50, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='address2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address Line 2'),
        ),
    ]
