# Generated by Django 4.1.5 on 2023-02-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0024_alter_carddetails_address1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carddetails',
            options={'verbose_name': 'Shipping Address'},
        ),
    ]
