# Generated by Django 4.1.5 on 2023-02-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0025_alter_carddetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carddetails',
            options={},
        ),
    ]
