# Generated by Django 4.1.5 on 2023-02-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0026_alter_carddetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
