# Generated by Django 4.1.5 on 2023-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0028_alter_pizza_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
