# Generated by Django 4.1.5 on 2023-02-26 17:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0029_alter_carddetails_id_alter_pizza_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pepperoni', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('peppers', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('onions', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='chicken',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ham',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='mushrooms',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='onions',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pepperoni',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='peppers',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pineapple',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='Pizza.toppings'),
        ),
    ]
