# Generated by Django 4.1.5 on 2023-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0030_toppings_remove_pizza_chicken_remove_pizza_ham_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='pepperoni',
            field=models.BooleanField(default=True),
        ),
    ]
