# Generated by Django 4.1.5 on 2023-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0031_alter_toppings_pepperoni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardDetails',
            new_name='CustomerDetails',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='chicken',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='ham',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='mushrooms',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='onions',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='pepperoni',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='peppers',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='pineapple',
        ),
        migrations.AddField(
            model_name='toppings',
            name='name',
            field=models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Chicken', 'Chicken'), ('Ham', 'Ham'), ('Pineapple', 'Pineapple'), ('Peppers', 'Peppers'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
