# Generated by Django 4.1.5 on 2023-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0032_rename_carddetails_customerdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='name',
            field=models.BooleanField(choices=[('Pepperoni', 'Pepperoni'), ('Chicken', 'Chicken'), ('Ham', 'Ham'), ('Pineapple', 'Pineapple'), ('Peppers', 'Peppers'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions')], default=False),
        ),
    ]
