# Generated by Django 4.1.5 on 2023-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0033_alter_toppings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='name',
            field=models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Chicken', 'Chicken'), ('Ham', 'Ham'), ('Pineapple', 'Pineapple'), ('Peppers', 'Peppers'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions')], max_length=20),
        ),
    ]
