# Generated by Django 4.1.5 on 2023-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0035_toppings_pepperoni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='pepperoni',
        ),
        migrations.AlterField(
            model_name='toppings',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
