# Generated by Django 4.1.5 on 2023-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0036_remove_toppings_pepperoni_alter_toppings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
