# Generated by Django 4.1.5 on 2023-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0037_alter_toppings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='chicken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='ham',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='mushrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='onions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pepperoni',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='peppers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pineapple',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
