# Generated by Django 4.1.5 on 2023-02-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0038_remove_pizza_toppings_pizza_chicken_pizza_ham_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='expiration',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='expiration_month',
            field=models.CharField(default=1, max_length=2, verbose_name='Expiration Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='expiration_year',
            field=models.IntegerField(default=1, max_length=4, verbose_name='Expiration Year'),
            preserve_default=False,
        ),
    ]
