# Generated by Django 4.1.5 on 2023-02-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0039_remove_customerdetails_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='expiration_year',
            field=models.IntegerField(verbose_name='Expiration Year'),
        ),
    ]
