# Generated by Django 4.1.5 on 2023-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0041_alter_customerdetails_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='expiration_month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Expiration Month'),
        ),
    ]
