# Generated by Django 4.1.5 on 2023-02-26 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0042_alter_customerdetails_expiration_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pepperoni',
            field=models.BooleanField(default=False),
        ),
    ]
