# Generated by Django 4.1.5 on 2023-02-27 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0047_remove_customerdetails_pizza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='olives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='cardnumber',
            field=models.CharField(max_length=19, validators=[django.core.validators.MinLengthValidator(19), django.core.validators.RegexValidator('^\\d{4}-|\\s\\d{4}-|\\s\\d{4}-|\\s\\d{4}', message='Please enter in the format 1234 1234 1234 1234')]),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='eircode',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('[A-Z]\\d{2}[A-Z]\\d[A-Z]\\d')]),
        ),
    ]
